name: Docker
on:
    workflow_call:
        inputs:
            username:
                description: 'Doker username'
                default: ''
                required: true
                type: string
            version:
                description: 'Version image docker'
                default: ''
                required: true
                type: string
        secrets:
            password:
                required: true

jobs:
    Docker-login-build-push:
        runs-on: ubuntu-latest
        steps:
            - name: Login Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ inputs.username }}
                password: ${{ secrets.password }}
      
            - name: Buind and push
              uses: docker/build-push-action@v1.1.0
              with:
                username: ${{ inputs.username }}
                password: ${{ secrets.password }}
                repository: alexsouzasilva/dvop-srv-consult-product
                tags: ${{ inputs.version }}, latest

