name: Executa Reusable Workflow

on: push

jobs:
  call-workflow:
    uses: ./.github/workflows/my-reusable.yaml
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
