name: Executa Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: alexdesouzasilva/reusables/.github/workflows/my_reusable_workflow.yaml@main
    with:
      environment: production
