name: Reusable Workflow Example

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: "dev"
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Print environment
        run: echo "Deploying to environment ${{ inputs.environment }}"